In [2]:
import pandas as pd

# **1. Extract Data**

We have different part of data stored in defferent sources

## 1.1. Enrollies' data

In [5]:
gg_sheet_id = "1VCkHwBjJGRJ21asd9pxW4_0z2PWuKhbLR3gUHm-p4GI"
url = "https://docs.google.com/spreadsheets/d/" + gg_sheet_id + "/export?format=xlsx"
df_enrollies = pd.read_excel(url, sheet_name="enrollies")

In [8]:
df_enrollies.head()

   enrollee_id      full_name      city gender
0         8949     Mike Jones  city_103   Male
1        29725    Laura Jones   city_40   Male
2        11561   David Miller   city_21    NaN
3        33241    Laura Davis  city_115    NaN
4          666  Alex Martinez  city_162   Male

## 1.2. Enrollies' Education

In [6]:
df_enrollies_education = pd.read_excel("enrollies_education.xlsx")

In [7]:
df_enrollies_education.head()

   enrollee_id enrolled_university education_level major_discipline
0         8949       no_enrollment        Graduate             STEM
1        29725       no_enrollment        Graduate             STEM
2        11561    Full time course        Graduate             STEM
3        33241                 NaN        Graduate  Business Degree
4          666       no_enrollment         Masters             STEM

## 1.3. Enrollies' working experience

In [10]:
df_enrollies_working_experience = pd.read_csv("https://assets.swisscoding.edu.vn/company_course/work_experience.csv")

In [11]:
df_enrollies_working_experience.head()

,enrollee_id,relevent_experience,experience,company_size,company_type,last_new_job
0,8949,Has relevent experience,>20,NaN,NaN,1
1,29725,No relevent experience,15,50-99,Pvt Ltd,>4
2,11561,No relevent experience,5,NaN,NaN,never
3,33241,No relevent experience,<1,NaN,Pvt Ltd,never
4,666,Has relevent experience,>20,50-99,Funded Startup,4

## 1.4. Training hours

In [12]:
! pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.2 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [15]:
from sqlalchemy import create_engine
import pymysql

db_connection = "mysql+pymysql://etl_practice:550814@112.213.86.31:3360/company_course"
engine = create_engine(db_connection)
df_training_hours = pd.read_sql("training_hours", con = engine)

In [16]:
df_training_hours.head()

   enrollee_id  training_hours
0         8949              36
1        29725              47
2        11561              83
3        33241              52
4          666               8

## 1.5. City development index

In [19]:
tables = pd.read_html("https://sca-programming-school.github.io/city_development_index/index.html")
df_city_development_index = tables[0]

In [20]:
df_city_development_index.head()

       City  City Development Index
0  city_103                   0.920
1   city_40                   0.776
2   city_21                   0.624
3  city_115                   0.789
4  city_162                   0.767

## 1.6 Employment

In [17]:
df_employment = pd.read_sql("SELECT * FROM employment", con = engine)

In [18]:
df_employment.head()

   enrollee_id  employed
0            1       0.0
1            2       1.0
2            4       0.0
3            5       0.0
4            7       0.0

# **2. Transfrom data**

## 2.1. Enrollies' data

In [21]:
df_enrollies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   full_name    19158 non-null  object
 2   city         19158 non-null  object
 3   gender       14650 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

Handing Column Type

In [22]:
df_enrollies.convert_dtypes().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  Int64
 1   full_name    19158 non-null  string
 2   city         19158 non-null  string
 3   gender       14650 non-null  string
dtypes: Int64(1), string(3)
memory usage: 617.5 KB

Handing Missing Value

In [23]:
gender_mode = df_enrollies["gender"].mode()[0]
df_enrollies["gender"].fillna(gender_mode, inplace=True)

<ipython-input-23-8f386d7a8aa0>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_enrollies["gender"].fillna(gender_mode, inplace=True)

## 2.2. Enrollies' Education

In [32]:
df_enrollies_education.sample(10)

       enrollee_id enrolled_university education_level major_discipline
18177        30483       No enrollment        Graduate             STEM
16891        22844       No enrollment         Masters             STEM
11947        24015    Full time course     High School              NaN
9070         30914    Full time course         Masters             STEM
4050         25401       No enrollment        Graduate             STEM
3354         22171    Part time course        Graduate             STEM
18061        11208    Full time course        Graduate             STEM
6472         17436    Full time course        Graduate             STEM
7453          5834       No enrollment         Masters             STEM
2242         26177       No enrollment        Graduate             STEM

In [25]:
df_enrollies_education.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  18772 non-null  object
 2   education_level      18698 non-null  object
 3   major_discipline     16345 non-null  object
dtypes: int64(1), object(3)
memory usage: 598.8+ KB

Handing Column Type

In [37]:
df_enrollies_education.loc[df_enrollies_education["enrolled_university"] == "no_enrollment", "enrolled_university"] = "No enrollment"

In [41]:
list_cate_cols = ["enrolled_university", "education_level", "major_discipline"]
df_enrollies_education[list_cate_cols] = df_enrollies_education[list_cate_cols].astype("category")

In [42]:
df_enrollies_education.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  19158 non-null  category
 2   education_level      19158 non-null  category
 3   major_discipline     19158 non-null  category
dtypes: category(3), int64(1)
memory usage: 206.7 KB

Handing Missing Value

In [35]:
df_enrollies_education["education_level"] = df_enrollies_education["education_level"].fillna("missing")
df_enrollies_education["enrolled_university"] = df_enrollies_education["enrolled_university"].fillna("missing")
df_enrollies_education["major_discipline"] = df_enrollies_education["major_discipline"].fillna("missing")

In [43]:
df_enrollies_education.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   enrolled_university  19158 non-null  category
 2   education_level      19158 non-null  category
 3   major_discipline     19158 non-null  category
dtypes: category(3), int64(1)
memory usage: 206.7 KB

## 2.3. Enrollies' working experience

In [44]:
df_enrollies_working_experience.sample(10)

,enrollee_id,relevent_experience,experience,company_size,company_type,last_new_job
14167,9252,No relevent experience,3,NaN,NaN,1
2405,23452,No relevent experience,5,NaN,NaN,NaN
9931,24043,No relevent experience,5,10000+,Pvt Ltd,never
16051,22770,Has relevent experience,3,100-500,Pvt Ltd,2
5266,8847,Has relevent experience,13,50-99,Public Sector,3
10267,25527,Has relevent experience,>20,100-500,Pvt Ltd,1
13666,32439,Has relevent experience,2,10/49,Pvt Ltd,2
2285,14976,Has relevent experience,10,NaN,NaN,never
15593,28903,Has relevent experience,9,100-500,Pvt Ltd,1
14977,11462,Has relevent experience,10,NaN,NaN,2

In [45]:
df_enrollies_working_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  object
 2   experience           19093 non-null  object
 3   company_size         13220 non-null  object
 4   company_type         13018 non-null  object
 5   last_new_job         18735 non-null  object
dtypes: int64(1), object(5)
memory usage: 898.2+ KB

In [46]:
df_enrollies_working_experience.loc[df_enrollies_working_experience["company_size"] == "10/49", "company_size"] = "10-49"

In [47]:
df_enrollies_working_experience['experience'] = df_enrollies_working_experience['experience'].fillna(df_enrollies_working_experience['experience'].mode()[0]).astype("category")

In [48]:
df_enrollies_working_experience['company_size'] = df_enrollies_working_experience['company_size'].fillna("missing").astype("category")
df_enrollies_working_experience['company_type'] = df_enrollies_working_experience['company_type'].fillna("missing").astype("category")
df_enrollies_working_experience['last_new_job'] = df_enrollies_working_experience['last_new_job'].fillna("missing").astype("category")

In [49]:
df_enrollies_working_experience['relevent_experience'] = df_enrollies_working_experience['relevent_experience'].astype("category")

In [50]:
df_enrollies_working_experience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   enrollee_id          19158 non-null  int64
 1   relevent_experience  19158 non-null  category
 2   experience           19158 non-null  category
 3   company_size         19158 non-null  category
 4   company_type         19158 non-null  category
 5   last_new_job         19158 non-null  category
dtypes: category(5), int64(1)
memory usage: 245.2 KB

## 2.4. Training hours

In [55]:
df_training_hours.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   enrollee_id     19158 non-null  int64
 1   training_hours  19158 non-null  int64
dtypes: int64(2)
memory usage: 299.5 KB

## 2.5. City development index

In [54]:
df_city_development_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   City                    123 non-null    object
 1   City Development Index  123 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.1+ KB

In [57]:
df_city_development_index.rename(columns={"City Development Index": "City_Development_Index"}, inplace=True)

In [58]:
df_city_development_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   City                    123 non-null    object
 1   City_Development_Index  123 non-null    float64
dtypes: float64(1), object(1)
memory usage: 2.1+ KB

## 2.6 Employment

In [53]:
df_employment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   enrollee_id  19158 non-null  int64
 1   employed     19158 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 299.5 KB

# **3. Load data**

In [56]:
db = "datawarehouse.db"

engine = ""

df_enrollies.to_sql("enrollies", con = engine, if_exists="replace", index = False)
df_enrollies_education.to_sql("enrollies_education", con = engine, if_exists="replace", index = False)
df_enrollies_working_experience.to_sql("enrollies_working_experience", con = engine, if_exists="replace", index = False)
df_training_hours.to_sql("training_hours", con = engine, if_exists="replace", index = False)
df_employment.to_sql("employee", con = engine, if_exists="replace", index = False)
df_city_development_index.to_sql("city_development", con = engine, if_exists="replace", index = False)

ArgumentError: Could not parse SQLAlchemy URL from string ''